config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/delete'

  root "root#index"

  get "root/index"

  post "root/showtimes"
  post "root/tickets"
  post "root/select_ticket/:id", to: "root#select_ticket"
  post "root/deselect_ticket/:id", to: "root#deselect_ticket"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :tickets

  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :showtimes, dependent: :destroy
  has_many :theatres, -> { distinct }, through: :showtimes
  has_many :tickets, through: :showtimes

  validates :name, uniqueness: true
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :theatre
  has_many :tickets, dependent: :destroy
end

app/models/showtime.rb
class Showtime < ApplicationRecord
  belongs_to :theatre
  belongs_to :movie
  has_many :tickets, dependent: :destroy

  validates :starts_at, uniqueness: {
    scope: :theatre, 
    message: "There can only be one showtime starting at the same time in a theatre!"
  }
end

app/models/theatre.rb
class Theatre < ApplicationRecord
  has_many :seats, dependent: :destroy
  has_many :showtimes, dependent: :destroy
  has_many :movies, through: :showtimes

  validates :name, uniqueness: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :seat
  belongs_to :showtime
  belongs_to :customer, optional: true

  enum status: {
    available: 0,
    claimed_pending_payment: 1,
    claimed: 2,
  }

  def cost
    seat.base_cost_cents + price_cents
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def set_current_customer
    @current_customer ||= begin
      current_customer_id = session[:current_customer_id]

      # if session[:current_customer_id] is nil, then this will also return nil
      current_customer = Customer.where(id: current_customer_id).first

      if current_customer.blank?
        session[:return_to] = request.path
        redirect_to sessions_new_path
      end

      current_customer
    end
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  before_action :set_current_customer

  # Note to reader: This is likely way, way to much for a single controller.
  # A lot of these actions should be split off into their own controllers.
  # For 2 day project though, this is fine.
  def index
    @movies = Movie.all
    @showtimes = []
    @purchase_preview = load_purchase_preview
  end

  def showtimes
    movie_id = params[:movie_id]

    @showtimes = Showtime.where(movie_id: movie_id)

    respond_to do |format|
      format.turbo_stream
    end
  end

  def tickets
    showtime_id = params.require(:showtime_id)

    @tickets = Ticket.where(showtime_id: showtime_id)
      .joins(:seat)
      .includes(:seat)
      .order("seats.id ASC")

    respond_to do |format|
      format.turbo_stream
    end
  end

  def select_ticket
    ticket_id = params.require(:id)

    @ticket = Ticket.where(id: params.require(:id)).first!

    if @ticket.claimed_pending_payment? && @ticket.customer != @current_customer
      respond_to do |format|
        format.turbo_stream { render template: "select_ticket_conflict" }
      end
      return
    end

    @ticket.update(status: :claimed_pending_payment, customer: @current_customer)

    @purchase_preview = load_purchase_preview

    respond_to do |format|
      format.turbo_stream
    end
  end

  def deselect_ticket
    ticket_id = params.require(:id)

    @ticket = Ticket.where(id: params.require(:id)).first!
    @ticket.update(status: :available, customer: nil)

    @purchase_preview = load_purchase_preview

    respond_to do |format|
      format.turbo_stream
    end
  end

  private def load_purchase_preview
    tickets = Ticket.claimed_pending_payment
      .where(customer: @current_customer)
      .includes(:seat)
      .includes(showtime: [:movie, :theatre])

    PurchasePreviewPresenter.new(tickets)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # You get the idea...
    customer = Customer.find_or_create_by!(name: params.require(:name))

    session[:current_customer_id] = customer.id

    redirect_to(session.fetch(:return_to, root_url))
  end

  def delete
    session.delete(:current_customer_id)
    redirect_to(sessions_new_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketzDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-white dark:bg-slate-900 text-neutral-900 dark:text-neutral-100">
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/root/_available_ticket.html.erb
<div class="p-4 rounded-lg shadow-lg flex w-16 justify-center bg-sky-600 <%= allow_hover ? "hover:bg-sky-400" : "" %>">
  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
  </svg>
</div>

app/views/root/_deselect_ticket_link.html.erb
<%= link_to(url_for(action: "deselect_ticket", id: ticket.id), { data: { "turbo-method" => "post" }, id: "#{dom_id(ticket)}_link" }) do %>
  <%= render "selected_ticket", allow_hover: true %>
<% end %>

app/views/root/_purchase_preview.html.erb
<h1 class="text-2xl"> Purchase Preview </h1>
<% if purchase_preview.empty? %>
  Please select a seat
<% else %> 
  <% purchase_preview.tickets_by_movie.each do |movie_name, tickets_at_showtime| %>
    <h2 class="text-xl mt-3"> <%= movie_name %> </h2>
    <% tickets_at_showtime.each do |showtime, tickets| %>
      <h4 class="text-lg mt-2"> <%= showtime %> </h4>
      <ul>
        <% tickets.each do |ticket| %>
          <li class="flex">
            <span>Seat <%= ticket.seat_number %> in <%= ticket.theatre_name %></span>
            <span class="flex-1 flex flex-row justify-end items-center border-b border-dotted border-neutral-900 dark:border-neutral-100 text-right">
              <%= ticket.price.format %>
              <%= link_to(url_for(action: "deselect_ticket", id: ticket.id), data: { "turbo-method" => "post" }) do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-red-600 dark:text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg>
              <% end %>
            </span>
          </li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
  <div class="flex pt-8 text-lg">
    <span>Subtotal:</span>
    <span class="flex-1 border-b border-dotted border-neutral-900 dark:border-neutral-100 text-right">
      <%= purchase_preview.subtotal.format %>
    </span>
  </div>
  <div class="flex pt-8 text-lg">
    <span>Taxes (<%= purchase_preview.tax_percentage %>%):</span>
    <span class="flex-1 border-b border-dotted border-neutral-900 dark:border-neutral-100 text-right">
      <%= purchase_preview.taxes.format %>
    </span>
  </div>
  <div class="flex pt-8 text-2xl">
    <span>Total:</span>
    <span class="flex-1 border-b border-dotted border-neutral-900 dark:border-neutral-100 text-right">
      <%= purchase_preview.total.format %> 
    </span>
  </div>
<% end %>

app/views/root/_select_ticket_link.html.erb
<%= link_to(url_for(action: "select_ticket", id: ticket.id), { data: { "turbo-method" => "post" }, id: "#{dom_id(ticket)}_link" }) do %>
  <%= render "available_ticket", allow_hover: true %>
<% end %>

app/views/root/_selected_ticket.html.erb
<div class="p-4 rounded-lg shadow-lg flex w-16 justify-center bg-green-600 <%= allow_hover ? "hover:bg-green-400" : "" %>">
  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
  </svg>
</div>

app/views/root/_selected_tickets.html.erb
<h1 class="text-2xl"> Purchase Preview </h1>
<% if selected_tickets.empty? %>
  Please select a ticket!
<% else %> 
  <% selected_tickets.by_movie.each do |movie_name, tickets_at_showtime| %>
    <h2 class="text-xl"> <%= movie_name %> </h2>
    <% tickets_at_showtime.each do |showtime, tickets| %>
      <h4 class="text-lg"> <%= showtime %> </h4>
      <ul>
        <% tickets.each do |ticket| %>
          <li class="flex">
            <span>Seat <%= ticket.seat_number %> in <%= ticket.theatre_name %></span>
            <span class="flex-1 border-b border-dotted border-black text-right">
              <%= ticket.price.format %>
            </span>
          </li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
  <div class="flex pt-8 text-lg">
    <span>Subtotal:</span>
    <span class="flex-1 border-b border-dotted border-black text-right">
      <%= selected_tickets.subtotal.format %>
    </span>
  </div>
  <div class="flex pt-8 text-lg">
    <span>Taxes (<%= selected_tickets.tax_percentage %>%):</span>
    <span class="flex-1 border-b border-dotted border-black text-right">
      <%= selected_tickets.taxes.format %>
    </span>
  </div>
  <div class="flex pt-8 text-2xl">
    <span>Total:</span>
    <span class="flex-1 border-b border-dotted border-black text-right">
      <%= selected_tickets.total.format %> 
    </span>
  </div>
<% end %>

app/views/root/_showtimes.html.erb
<%= form_tag(url_for(action: "tickets"), method: :post) do %>
  <%= select_tag("showtime_id",
                 options_for_select(showtimes.map { |showtime| [showtime.starts_at.to_fs(:showtime_full), showtime.id]}),
                 prompt: "Select a showtime",
                 onchange: "Turbo.navigator.submitForm(this.form)",
                 class: "w-[275px] bg-slate-50 text-neutral-900 dark:bg-slate-700 dark:text-neutral-100") %>
<% end %>

app/views/root/_ticket_link.html.erb
<%= link_to(url_for(action: "select_ticket", id: ticket.id), { data: { "turbo-method" => "post" }, id: "#{dom_id(ticket)}_link", class: "p-4 rounded-lg shadow-lg flex justify-center bg-violet-600 hover:bg-violet-400" }) do %>
  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
  </svg>
        <% end %>

app/views/root/_unavailable_ticket.html.erb
<div id="<%= "#{dom_id(ticket)}_link" %>" class="p-4 rounded-lg shadow-lg flex w-16 justify-center bg-stone-800 dark:bg-stone-400 opacity-50">
  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
  </svg>
</div>

app/views/root/deselect_ticket.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@ticket)}_link" do %>
  <%= render "select_ticket_link", ticket: @ticket %>
<% end %>

<%= turbo_stream.update "purchase-preview" do %>
  <%= render "purchase_preview", purchase_preview: @purchase_preview %>
<% end %>

<%= turbo_stream.update "notices" do %>
<% end %>

app/views/root/index.html.erb
<div>
  <div class="flex items-center">
    <h1 class="font-bold text-4xl">Let's buy some tickets!</h1>
    <%= button_to "(Log out)", sessions_delete_path, method: :delete, class: "text-blue-400 ml-2 hover:text-blue-400 hover:underline" %>
  </div>

  <%= turbo_frame_tag("notices", class: "h-[48px] my-2 w-auto block") -%>

  <div class="flex flex-row">
    <div class="flex flex-col">
      <div class="h-16 flex items-start pt-1">
        <%= turbo_frame_tag("select-movie", class:"pr-10") do %>
          <div id="select-movie">
            <%= form_tag(url_for(action: "showtimes"), method: :post ) do %>
              <%= select_tag "movie_id", options_from_collection_for_select(@movies, "id", "name"), prompt: "Select a movie", onchange: "Turbo.navigator.submitForm(this.form)", class: "bg-slate-50 text-neutral-900 dark:bg-slate-700 dark:text-neutral-100" %>
            <% end %>
          </div>
        <% end %>

        <%= turbo_frame_tag("select-showtime") do %>
          <%= render "showtimes", showtimes: [] %>
        <% end %>
      </div>

      <div class="flex flex-col">
        <%= turbo_frame_tag("tickets-for-showtime", class: "flex flex-col") -%>
      </div>
    </div>

    <div class="ml-20 flex-1">
      <%= turbo_frame_tag("purchase-preview") do %>
        <%= render "purchase_preview", purchase_preview: @purchase_preview %>
      <% end %>
    </div>
  </div>
</div>

app/views/root/select_ticket.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@ticket)}_link" do %>
  <%= render "deselect_ticket_link", ticket: @ticket %>
<% end %>

<%= turbo_stream.update "purchase-preview" do %>
  <%= render "purchase_preview", purchase_preview: @purchase_preview %>
<% end %>

<%= turbo_stream.update "notices" do %>
<% end %>

app/views/root/showtimes.turbo_stream.erb
<%= turbo_stream.update "select-showtime" do %>
  <%= render "showtimes", showtimes: @showtimes %>
<% end %>

<%= turbo_stream.update "tickets-for-showtime" do %>
<% end %>

app/views/root/tickets.turbo_stream.erb
<%= turbo_stream.update "tickets-for-showtime" do %>
  <div class="grid grid-cols-5 gap-4 justify-items-center">
    <% @tickets.each do |ticket| %>
      <% if ticket.available? %>
        <%= render "select_ticket_link", ticket: ticket %>
      <% elsif ticket.claimed_pending_payment? && ticket.customer == @current_customer %>
        <%= render "deselect_ticket_link", ticket: ticket %>
      <% else %>
        <%= render "unavailable_ticket", ticket: ticket %>
      <% end %>
    <% end %>
  </div>

  <img src="https://via.placeholder.com/470x90.png?text=SCREEN" class="mt-5" />

  <%= render "legend" %>
<% end %>